
# Site settings
title: You SHAN
name: You SHAN
subtitle:  A Decision Maker
email: shanyouleo@gmail.com
description: >
   Economist
baseurl: ""
url: "https://shanyouleo.github.io/"
github_username:  shanyouleo
disqus_baseurl: "https://shanyouleo.github.io/"
disqus_shortname: https-shanyouleo-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "You SHAN"





