
# Site settings
title: You SHAN
name: You SHAN
subtitle:  Economist
email: shanyouleo@gmail.com
description: >
   Economist
baseurl: ""
url: "https://shanyouleo.github.io/"
github_username:  shanyouleo
disqus_baseurl: "https://shanyouleo.github.io/"
disqus_shortname: https-shanyouleo-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "You SHAN"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url: https://github.com/pesoto
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Paul E. Soto
    url: https://www.linkedin.com/in/paul-e-soto-2705ab218
    desc: Connect with me on LinkedIn
    share: false
